import json
import os

from typing import Dict,List,Any,NamedTuple

class RegionRow(NamedTuple):
    id: str
    name: str

class ResourceRow(NamedTuple):
    name: str

class DropElement(NamedTuple):
    dest: str
    chance: int

class MonsterRow(NamedTuple):
    name: str
    class_name: str
    drops: list[DropElement]

class RewardElement(NamedTuple):
    skill_name: str
    skill_level: int

class QuestRow(NamedTuple):
    name: str
    rewards: list[RewardElement]

class RuleElement(NamedTuple):
    type: str
    value: str

class SubQuestRow(NamedTuple):
    name: str
    parent_quest: str
    rule: list[RuleElement]

class EntranceRow(NamedTuple):
    source: str
    dest: str
    rule: list[RuleElement]

class TrainingRow(NamedTuple):
    product: str
    skill_name: str
    normal_level: int
    brutal_level: int
    meme_level: int

class LocationRow(NamedTuple):
    name: str
    rule: list[RuleElement]

this_dir = os.path.dirname(os.path.abspath(__file__))

chunks:Dict[str, Any] = {}
monster_list:List[MonsterRow] = []
resource_list:List[ResourceRow] = []
regions_list:list[RegionRow] = []

monsters:list[str] = []
resources:list[str] = []
regions:list[str] = []


rr_entrances: list[EntranceRow] = []
re_entrances: list[EntranceRow] = []
ee_entrances: list[EntranceRow] = []
rm_entrances: list[EntranceRow] = []
me_entrances: list[EntranceRow] = []

def str_format(s) -> str:
    ret_str = s.replace("'", "\\'")
    return f"'{ret_str}'"


def str_list_to_py(str_list) -> str:
    ret_str = "["
    for s in str_list:
        ret_str += str_format(s)
    ret_str += "]"
    return ret_str

def chunk_init(chunk_name,chunk_id,chunk):
    chunk["Chunk_Name"] = chunk_name
    chunk["Contents"] = []
    if chunk_name not in regions:
        regions.append(chunk_name)
    if "Object" in chunk:
        for object in chunk["Object"].keys():
            if not object in resources:
                resources.append(object)
                resource_list.append(ResourceRow(object))
            chunk["Contents"].append(object)
            temp_entrance = EntranceRow(chunk_id,object,[])
            re_entrances.append(temp_entrance)
    if "Monster" in chunk:
        for monster in chunk["Monster"].keys():
            if not monster in monsters:
                monsters.append(monster)
            chunk["Contents"].append(monster)
            temp_entrance = EntranceRow(chunk_id,monster,[])
            rm_entrances.append(temp_entrance)
    chunks[chunk_id]=chunk
    regions_list.append(RegionRow(chunk_id,chunk_name))

with open(os.path.join(this_dir, "chunkpicker-chunkinfo-export.json"), 'r') as localJSON:
    exportedJSON = json.load(localJSON)
    for chunk_id,chunk in exportedJSON["chunks"].items():
        chunk_name = ""
        if "Nickname" in chunk:
            chunk_name = chunk["Nickname"]
        elif "Name" in chunk:
            chunk_name = chunk["Name"]
        if "Sections" in chunk:
            if len(chunk) > 2: #should be nickname and sections
                chunk_init(chunk_name,chunk_id,chunk)#but there might be something else
            for section_id, section in chunk["Sections"].items():
                chunk_init(chunk_name,chunk_id+"-"+section_id,section)
        else:
            chunk_init(chunk_name,chunk_id,chunk)
    for macro_name, macro_list in exportedJSON["codeItems"]["itemsPlus"].items():
        if macro_name not in resources:
            resources.append(macro_name)
            resource_list.append(ResourceRow(macro_name))
            for sub_item in macro_list:
                if sub_item in resources:
                    ee_entrances.append(EntranceRow(sub_item,macro_name,[]))
    for chunk_id,sections in exportedJSON["sections"].items():
        for section_id,connections in sections.items():
            section_name = f"{chunk_id}-{section_id}"
            if section_id == "0":
                section_name = chunk_id
            if section_name not in chunks:
                print("PANIC! : "+ section_name)
                continue
            for connection in connections:
                if connection not in chunks:
                    if f"{connection}-1" in chunks:
                        connection += "-1"
                    else:
                        print("PANIC! : " + connection)
                        continue
                if "Connect" not in chunks[section_name]:
                    chunks[section_name]["Connect"] = {}
                chunks[section_name]["Connect"][connection] = True
                rr_entrances.append(EntranceRow(section_name,connection,[]))
                   
                    

with open(os.path.join(this_dir, "regions_generated2.py"), "w+") as regPyFile:
            regPyFile.write('"""\nThis file was auto generated by LogicCSVToPython.py\n"""\n')
            regPyFile.write("from ..Regions import RegionRow,EntranceRow\n")
            regPyFile.write("\n")
            regPyFile.write("region_rows = [\n")

            for region_row in regions_list:
                row_line = "RegionRow("
                row_line += str_format(region_row.id)
                row_line += ","
                row_line += str_format(region_row.name)
                row_line += ")"
                regPyFile.write(f"\t{row_line},\n")
            
            regPyFile.write("]\n\n")

            regPyFile.write("rr_entrances = [\n")

            for entrance_row in rr_entrances:
                row_line = "EntranceRow("
                row_line += str_format(entrance_row.source)
                row_line += ","
                row_line += str_format(entrance_row.dest)
                row_line += ",["
                for rule in entrance_row.rule:
                    pass # do later lol
                row_line += "])"
                regPyFile.write(f"\t{row_line},\n")
            
            regPyFile.write("]\n\n")

            regPyFile.write("re_entrances = [\n")

            for entrance_row in re_entrances:
                row_line = "EntranceRow("
                row_line += str_format(entrance_row.source)
                row_line += ","
                row_line += str_format(entrance_row.dest)
                row_line += ",["
                for rule in entrance_row.rule:
                    pass # do later lol
                row_line += "])"
                regPyFile.write(f"\t{row_line},\n")
            
            regPyFile.write("]\n\n")


            

#with open(os.path.join(this_dir, "resources_generated2.py"),"w+") as resPyFile:
#            resPyFile.write('"""\nThis file was auto generated by LogicCSVToPython.py\n"""\n')
#            resPyFile.write("from ..Regions import ResourceRow\n")
#            resPyFile.write("\n")
#            resPyFile.write("resource_rows = [\n")
#            for row in resources:
#                row_line = f'ResourceRow("{row}")'
#                resPyFile.write(f"\t{row_line},\n")
#            resPyFile.write("]\n")