from typing import NamedTuple

from BaseClasses import Location

class LocationInfo(NamedTuple):
    name: str
    id: int
    campaign: str
    mission: str


all_locations = [
    LocationInfo("In the Thick of It - Find Einstein", 0, "Allied Campaign", "allies-01"),
    LocationInfo("In the Thick of It - Protect all civilians", 1, "Allied Campaign", "allies-01"),
    LocationInfo("In the Thick of It - Wait for the helicopter and extract Einstein", 2, "Allied Campaign", "allies-01"),
    LocationInfo("Five to One - Secure the convoy's path", 3, "Allied Campaign", "allies-02"),
    LocationInfo("Five to One - Eliminate the entire Soviet presence in this area", 4, "Allied Campaign", "allies-02"),
    LocationInfo("Five to One - Escort the convoy", 5, "Allied Campaign", "allies-02"),
    LocationInfo("Dead End - Destroy All Bridges", 6, "Allied Campaign", "allies-03"),
    LocationInfo("Dead End - Destroy all Soviet oil pumps", 7, "Allied Campaign", "allies-03"),
    LocationInfo("Dead End - Free all Allied soldiers and keep them alive", 8, "Allied Campaign", "allies-03"),
    LocationInfo("Dead End A - Destroy All Bridges", 9, "Allied Campaign", "allies-03"),
    LocationInfo("Dead End A - Destroy all Soviet oil pumps", 10, "Allied Campaign", "allies-03"),
    LocationInfo("Dead End A - Free all Allied soldiers and keep them alive", 11, "Allied Campaign", "allies-03"),
    LocationInfo("Dead End B - Destroy All Bridges", 12, "Allied Campaign", "allies-03"),
    LocationInfo("Dead End B - Find our lost tanks", 13, "Allied Campaign", "allies-03"),
    LocationInfo("Dead End B - Free all Allied soldiers and keep them alive", 14, "Allied Campaign", "allies-03"),
    LocationInfo("Ten to One - Destroy all Soviet units and buildings in this region", 15, "Allied Campaign", "allies-04"),
    LocationInfo("Ten to One - Eliminate all passing Soviet convoys", 16, "Allied Campaign", "allies-04"),
    LocationInfo("Tanya's Tale - Rescue Tanya", 17, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale - Eliminate all Soviet units in this area", 18, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale - Infiltrate the Soviet War Factory", 19, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale - Destroy all four SAM Sites blocking our reinforcements' helicopter from landing", 20,
                 "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale A - Rescue Tanya", 21, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale A - Eliminate all Soviet units in this area", 22, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale A - Infiltrate the Soviet War Factory", 23, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale A - Destroy all four SAM Sites blocking our reinforcements' helicopter from landing", 24,
                 "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale B - Rescue Tanya", 25, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale B - Eliminate all Soviet units in this area", 26, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale B - Infiltrate the Soviet War Factory", 27, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale B - Destroy all four SAM Sites blocking our reinforcements' helicopter from landing", 28,
                 "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale C - Rescue Tanya", 29, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale C - Eliminate all Soviet units in this area", 30, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale C - Infiltrate the Soviet War Factory", 31, "Allied Campaign", "allies-05"),
    LocationInfo("Tanya's Tale C - Destroy all four SAM Sites blocking our reinforcements' helicopter from landing", 32,
                 "Allied Campaign", "allies-05"),
    LocationInfo("Cripple Iron Curtain Research - Secure a foothold and build a Naval Yard", 33, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research - Capture the Radar Dome near the shore", 34, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research - Infiltrate one of the Soviet tech centers with a spy", 35, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research - Destroy all Soviet buildings and units in the area", 36, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research A - Secure a foothold and build a Naval Yard", 37, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research A - Capture the Radar Dome near the shore", 38, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research A - Infiltrate one of the Soviet tech centers with a spy", 39, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research A - Destroy all Soviet buildings and units in the area", 40, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research B - Secure a foothold and build a Naval Yard", 41, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research B - Capture the Radar Dome near the shore", 42, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research B - Infiltrate one of the Soviet tech centers with a spy", 43, "Allied Campaign", "allies-06"),
    LocationInfo("Cripple Iron Curtain Research B - Destroy all Soviet buildings and units in the area", 44, "Allied Campaign", "allies-06"),
    LocationInfo("Sunken Treasure - Capture the Radar Dome", 45, "Allied Campaign", "allies-07"),
    LocationInfo("Sunken Treasure - Destroy all Soviet Submarine Pens", 46, "Allied Campaign", "allies-07"),
    LocationInfo("Sunken Treasure - Clear the area of all Submarine activity", 47, "Allied Campaign", "allies-07"),
    LocationInfo("Protect the Chronosphere - Defend the Chronosphere and Technology Center at all costs", 48, "Allied Campaign", "allies-08"),
    LocationInfo("Protect the Chronosphere - The Chronosphere must have power when the timer runs out", 49, "Allied Campaign", "allies-08"),
    LocationInfo("Protect the Chronosphere - Evacuate all scientists from the island to the west", 50, "Allied Campaign", "allies-08"),
    LocationInfo("Protect the Chronosphere A - Defend the Chronosphere and Technology Center at all costs", 51, "Allied Campaign", "allies-08"),
    LocationInfo("Protect the Chronosphere A - The Chronosphere must have power when the timer runs out", 52, "Allied Campaign", "allies-08"),
    LocationInfo("Protect the Chronosphere A - Evacuate all scientists from the island to the west", 53, "Allied Campaign", "allies-08"),
    LocationInfo("Protect the Chronosphere B - Defend the Chronosphere and Technology Center at all costs", 54, "Allied Campaign", "allies-08"),
    LocationInfo("Protect the Chronosphere B - The Chronosphere must have power when the timer runs out", 55, "Allied Campaign", "allies-08"),
    LocationInfo("Protect the Chronosphere B - Evacuate all scientists from the island to the east", 56, "Allied Campaign", "allies-08"),
    LocationInfo("Evacuate Kosygin - Extract Kosygin and get him back to your base", 57, "Allied Campaign", "allies-09"),
    LocationInfo("Evacuate Kosygin - Infiltrate the Soviet Command Center and contact Kosygin", 58, "Allied Campaign", "allies-09"),
    LocationInfo("Suspicion - Find a way to take the atomic weapons offline", 59, "Allied Campaign", "allies-10"),
    LocationInfo("Suspicion - Capture the enemy Command Center. Hurry!", 60, "Allied Campaign", "allies-10"),
    LocationInfo("Evidence - Get your engineers to each launch control center", 61, "Allied Campaign", "allies-10"),
    LocationInfo("Evidence - Spare the scientists; they are more valuable as prisoners of war.", 62, "Allied Campaign", "allies-10"),
    LocationInfo("Evidence - Find Tanya", 63, "Allied Campaign", "allies-10"),
    LocationInfo("Focused Blast - Place explosive charges on all generators", 64, "Allied Campaign", "allies-13"),
    LocationInfo("Focused Blast - Secure the base's supply cache", 65, "Allied Campaign", "allies-13"),
    LocationInfo("Lesson in Blood - Raze the Village", 66, "Soviet Campaign", "soviet-01"),
    LocationInfo("The Thin Red Line - Protect the Command Center", 67, "Soviet Campaign", "soviet-02"),
    LocationInfo("The Thin Red Line - Destroy all Allied units and structures", 68, "Soviet Campaign", "soviet-02"),
    LocationInfo("The Thin Red Line A - Protect the Command Center", 69, "Soviet Campaign", "soviet-02"),
    LocationInfo("The Thin Red Line A - Destroy all Allied units and structures", 70, "Soviet Campaign", "soviet-02"),
    LocationInfo("The Thin Red Line B - Protect the Command Center", 71, "Soviet Campaign", "soviet-02"),
    LocationInfo("The Thin Red Line B - Destroy all Allied units and structures", 72, "Soviet Campaign", "soviet-02"),
    LocationInfo("Covert cleanup - Kill the enemy spy", 73, "Soviet Campaign", "soviet-03"),
    LocationInfo("Covert cleanup - Clear the nearby farm for reinforcements", 74, "Soviet Campaign", "soviet-03"),
    LocationInfo("Covert cleanup - Scavenge civilian buildings for supplies", 75, "Soviet Campaign", "soviet-03"),
    LocationInfo("Behind the Lines - Destroy the Allied Radar Dome to prevent reinforcements", 76, "Soviet Campaign", "soviet-04"),
    LocationInfo("Behind the Lines - Defeat the Allied Forces", 77, "Soviet Campaign", "soviet-04"),
    LocationInfo("Behind the Lines A - Destroy the Allied Radar Dome to prevent reinforcements", 78, "Soviet Campaign", "soviet-04"),
    LocationInfo("Behind the Lines A - Defeat the Allied Forces", 79, "Soviet Campaign", "soviet-04"),
    LocationInfo("Behind the Lines B - Destroy the Allied Radar Dome to prevent reinforcements", 80, "Soviet Campaign", "soviet-04"),
    LocationInfo("Behind the Lines B - Defeat the Allied Forces", 81, "Soviet Campaign", "soviet-04"),
    LocationInfo("Distant Thunder - Capture the Radar Dome", 82, "Soviet Campaign", "soviet-05"),
    LocationInfo("Distant Thunder - Defend the Radar Dome", 83, "Soviet Campaign", "soviet-05"),
    LocationInfo("Distant Thunder - Defeat the Allied Forces", 84, "Soviet Campaign", "soviet-05"),
    LocationInfo("Bridge over the River - Escort the convoy", 85, "Soviet Campaign", "soviet-06"),
    LocationInfo("Bridge over the River - Destroy or capture the Allied Radar Dome to stop enemy reinforcements", 86,
                 "Soviet Campaign", "soviet-06"),
    LocationInfo("Bridge over the River - Keep all trucks alive", 87, "Soviet Campaign", "soviet-06"),
    LocationInfo("Bridge over the River A - Escort the convoy", 88, "Soviet Campaign", "soviet-06"),
    LocationInfo("Bridge over the River A - Destroy or capture the Allied Radar Dome to stop enemy reinforcements", 89,
                 "Soviet Campaign", "soviet-06"),
    LocationInfo("Bridge over the River A - Keep all trucks alive", 90, "Soviet Campaign", "soviet-06"),
    LocationInfo("Bridge over the River B - Escort the convoy", 91, "Soviet Campaign", "soviet-06"),
    LocationInfo("Bridge over the River B - Destroy or capture the Allied Radar Dome to stop enemy reinforcements", 92,
                 "Soviet Campaign", "soviet-06"),
    LocationInfo("Bridge over the River B - Keep all trucks alive", 93, "Soviet Campaign", "soviet-06"),
    LocationInfo("Core of the Matter - Deactivate the security system", 94, "Soviet Campaign", "soviet-07"),
    LocationInfo("Core of the Matter - Rescue the engineers", 95, "Soviet Campaign", "soviet-07"),
    LocationInfo("Core of the Matter - Get the engineers to the coolant stations", 96, "Soviet Campaign", "soviet-07"),
    LocationInfo("Core of the Matter - Use an Engineer to reprogram the security system", 97, "Soviet Campaign", "soviet-07"),
    LocationInfo("Core of the Matter - Get an Engineer to the reactor core", 98, "Soviet Campaign", "soviet-07"),
    LocationInfo("Core of the Matter - Free the dogs", 99, "Soviet Campaign", "soviet-07"),
    LocationInfo("Investigate Elba Island - Destroy all Allied units and structures", 100, "Soviet Campaign", "soviet-08"),
    LocationInfo("Investigate Elba Island - Destroy the village of Allied sympathizers", 101, "Soviet Campaign", "soviet-08"),
    LocationInfo("Investigate Elba Island A - Destroy all Allied units and structures", 102, "Soviet Campaign", "soviet-08"),
    LocationInfo("Investigate Elba Island A - Destroy the village of Allied sympathizers", 103, "Soviet Campaign", "soviet-08"),
    LocationInfo("Investigate Elba Island B - Destroy all Allied units and structures", 104, "Soviet Campaign", "soviet-08"),
    LocationInfo("Investigate Elba Island B - Destroy the village of Allied sympathizers", 105, "Soviet Campaign", "soviet-08"),
    LocationInfo("Liability Elimination - Destroy the stolen convoy truck - don't let it escape", 106, "Soviet Campaign", "soviet-09"),
    LocationInfo("Liability Elimination - Defend our forward Command Center", 107, "Soviet Campaign", "soviet-09"),
    LocationInfo("Overseer - Escort the convoy through the mountain pass", 108, "Soviet Campaign", "soviet-10"),
    LocationInfo("Overseer - Ensure no truck is lost", 109, "Soviet Campaign", "soviet-10"),
    LocationInfo("Overseer - Do not squander any of our new MiG aircraft", 110, "Soviet Campaign", "soviet-10"),
    LocationInfo("Sunk Costs - Destroy all Allied units and structures", 111, "Soviet Campaign", "soviet-11"),
    LocationInfo("Sunk Costs A - Destroy all Allied units and structures", 112, "Soviet Campaign", "soviet-11"),
    LocationInfo("Sunk Costs B - Destroy all Allied units and structures", 113, "Soviet Campaign", "soviet-11"),
    LocationInfo("Capture the Chronosphere - Destroy the Allied radar sites before approaching the Chronosphere", 114,
                 "Soviet Campaign", "soviet-13"),
    LocationInfo("Capture the Chronosphere - Capture the Chronosphere", 115, "Soviet Campaign", "soviet-13"),
    LocationInfo("Capture the Chronosphere A - Destroy the Allied radar sites before approaching the Chronosphere", 116,
                 "Soviet Campaign", "soviet-13"),
    LocationInfo("Capture the Chronosphere A - Capture the Chronosphere", 117, "Soviet Campaign", "soviet-13"),
    LocationInfo("Capture the Chronosphere B - Destroy the Allied radar sites before approaching the Chronosphere", 118,
                 "Soviet Campaign", "soviet-13"),
    LocationInfo("Capture the Chronosphere B - Capture the Chronosphere", 119, "Soviet Campaign", "soviet-13"),

]

class OpenRALocation(Location):
    game = "OpenRA"

