from enum import StrEnum


class RegionNames(StrEnum):
    Lumbridge = "Lumbridge"
    Lumbridge_Swamp = "Lumbridge Swamp"
    Lumbridge_Farms = "Lumbridge Farms"
    HAM_Hideout = "HAM Hideout"
    Draynor_Village = "Draynor Village"
    Wizards_Tower = "Wizard's Tower"
    Al_Kharid = "Al Kharid"
    Cathraed_Abbey = "Cathraed Abbey"
    South_Of_Varrock = "South of Varrock"
    Central_Varrock = "Central Varrock"
    Varrock_Palace = "Varrock Palace"
    East_Of_Varrock = "East of Varrock"
    West_Varrock = "West Varrock"
    Edgeville = "Edgeville"
    Barbarian_Village = "Barbarian Village"
    Monastery = "Monastery"
    Ice_Mountain = "Ice Mountain"
    Dwarven_Mines = "Dwarven Mines"
    Falador = "Falador"
    Falador_Farm = "Falador Farm"
    Crafting_Guild = "Crafting Guild"
    Rimmington = "Rimmington"
    Port_Sarim = "Port Sarim"
    Mudskipper_Point = "Mudskipper Point"
    Karamja = "Karamja"
    Corsair_Cove = "Corsair Cove"
    Wilderness = "The Wilderness"
    Crandor = "Crandor"
